// <auto-generated />
using FieldMerge.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FieldMerge.Data.Migrations
{
    [DbContext(typeof(FieldCodeContext))]
    [Migration("20220315222215_AutoIncrementId")]
    partial class AutoIncrementId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("FieldMerge.Data.Models.FieldCodePattern", b =>
                {
                    b.Property<int>("PatternId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PatternFrom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatternTo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PatternId");

                    b.ToTable("FieldCodePatterns");
                });
#pragma warning restore 612, 618
        }
    }
}
